# Project Name
#TARGET = biquad
TARGET = test

# Sources
#CPP_SOURCES += biquad.cpp
CPP_SOURCES = test.cpp

# Library Locations
LIBDAISY_DIR ?= ../../../libDaisy
DAISYSP_DIR ?= ../../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

